import type { BlogPost } from "./blog-posts";

export const EXTRA_POSTS: BlogPost[] = [
  {
    slug: "whatsapp-not-showing-new-contacts-fix",
    title: "WhatsApp Not Showing Newly Saved Contacts? 8 Fixes That Work on Android and iPhone",
    description:
      "Imported a VCF file but the new numbers are missing in WhatsApp? Here are the eight most common causes and the exact steps to fix each one on Android and iPhone.",
    date: "2026-03-02",
    readMinutes: 6,
    tags: ["WhatsApp", "Troubleshooting", "Contacts"],
    body: [
      "You imported a contact file, the names appear in your phone book, yet WhatsApp acts like they do not exist. This is one of the most common problems after a bulk import, and it is almost always fixable in under five minutes.",
      "## 1. Refresh the contact list inside WhatsApp",
      "On Android, open WhatsApp, tap the green New chat button, open the three-dot menu and choose Refresh. On iPhone, pull down on the New chat screen. WhatsApp does not always re-read your address book on its own, especially after a large import.",
      "## 2. Check that WhatsApp has contacts permission",
      "On Android go to Settings, Apps, WhatsApp, Permissions and make sure Contacts is allowed. On iPhone go to Settings, scroll to WhatsApp and switch Contacts on. Without this permission WhatsApp can only show numbers you have chatted with before.",
      "## 3. Confirm the contacts are saved to a visible account",
      "On Android, contacts can be saved to the phone, a SIM card or a Google account. If the import went to an account that is hidden in your Contacts app display settings, WhatsApp will not see them. Open Contacts, tap the menu, choose Settings, then Contacts to display, and select All contacts.",
      "## 4. Make sure the numbers include the country code",
      "A number saved as 0813 000 0000 usually works inside Nigeria, but if you travel or use a foreign SIM, WhatsApp may misread it. Numbers stored as +234 813 000 0000 are matched far more reliably.",
      "## 5. Wait for the sync to finish",
      "Importing a few thousand contacts triggers a background sync. Give your phone a few minutes on a stable connection, and avoid force-closing the Contacts app while it works.",
      "## 6. Turn contact sync back on (Android)",
      "In Settings, open Accounts, pick your Google account, then Account sync and make sure Contacts is switched on. If it was off, new entries stay stuck on the device and never reach WhatsApp.",
      "## 7. Remember that only WhatsApp users appear",
      "WhatsApp lists only numbers that are registered on WhatsApp. If a number is saved but not on the app, it will not show up as a chat option. That is normal and not an error.",
      "## 8. Restart, then update",
      "Restart the phone and update WhatsApp from the Play Store or App Store. Old versions have had contact-sync bugs that were fixed in later releases.",
      "If all eight steps fail, export a small test file with ten contacts, import it, and see whether those ten appear. If they do, your phone is fine and the issue is only the size or format of the larger file.",
    ],
  },
  {
    slug: "why-cant-i-see-whatsapp-status-views",
    title: "Why Can't I See Who Viewed My WhatsApp Status? Every Reason Explained",
    description:
      "Status view count stuck at zero or the viewer list is missing? Learn the real reasons, from read receipts to unsaved numbers, and how to get accurate view data again.",
    date: "2026-03-09",
    readMinutes: 5,
    tags: ["WhatsApp Status", "Troubleshooting", "Analytics"],
    body: [
      "A Status that shows no viewers can mean nobody watched it, or it can mean WhatsApp is hiding the information. Knowing which one it is saves you from changing a strategy that was actually working.",
      "## Reason 1: Read receipts are switched off",
      "If you turn off read receipts in Settings, Privacy, you stop seeing who viewed your Status, and others stop seeing when you view theirs. The setting works both ways. Switch it back on if you want view data.",
      "## Reason 2: Viewers do not have your number saved",
      "Status updates are shown to people who are in your address book and who also have you saved. If a customer only has you inside a group or an unsaved chat, they will not see your Status. This is why growing the number of phones your number is saved in matters so much.",
      "## Reason 3: Your privacy list excludes people",
      "Open Status privacy and check which option is selected: My contacts, My contacts except, or Only share with. A forgotten exclusion list can quietly cut your audience in half.",
      "## Reason 4: The update is older than 24 hours",
      "Status disappears after 24 hours, and so does the viewer list. If you want a record, check the same day or screenshot the numbers.",
      "## Reason 5: A weak connection delayed the upload",
      "A Status stuck on a clock icon has not been delivered, so nobody could view it. Retry on a better connection or compress large videos.",
      "## Reason 6: People mute your Status",
      "Viewers can mute you, which pushes your updates to the bottom of their list. They can still open it, but they rarely do. If your views are dropping week after week, posting too often is the usual cause.",
      "## How to get real numbers",
      "Track views for seven days at the same posting times, then compare. One bad post tells you nothing; a week of data shows you which time slots and content types actually earn attention.",
      "Fix privacy and read receipts first, grow the number of people who have saved you, and keep a steady posting rhythm. Those three changes explain most of the difference between low and high view counts.",
    ],
  },
  {
    slug: "how-to-check-who-viewed-whatsapp-status",
    title: "How to Check Who Viewed Your WhatsApp Status (And Use It to Find Buyers)",
    description:
      "Step-by-step instructions to see your Status viewers on Android and iPhone, plus a simple method for turning viewers into customers without being pushy.",
    date: "2026-03-16",
    readMinutes: 5,
    tags: ["WhatsApp Status", "Sales", "Tutorial"],
    body: [
      "Your Status viewer list is a free lead list. The people who watch your updates repeatedly are warmer than any stranger you could message, and most vendors never look at it.",
      "## How to see viewers on Android",
      "Open the Updates tab, tap My status, then swipe up on the update or tap the eye icon at the bottom. You will see every viewer with the time they watched. Tap a name to open the chat.",
      "## How to see viewers on iPhone",
      "Go to the Status tab, tap My Status, and tap the eye icon on the update. The list shows the viewers in the order they watched.",
      "## What you will not see",
      "You will not see views if read receipts are off, and you cannot see views after 24 hours. People who watched without having your number saved will not appear either, because they could not see the update at all.",
      "## Spot your repeat viewers",
      "Write down the names that appear on three or more updates in a week. These are people who find your content interesting or who are quietly considering a purchase. They deserve a personal touch.",
      "## Reply to reactions, not just messages",
      "When someone reacts or replies to a Status, answer within the hour if you can. A short, friendly response such as 'Glad you liked it, want the price list?' converts better than a copied sales pitch.",
      "## Never message every viewer",
      "Sending the same message to everyone who watched looks like spam and risks being reported. Pick a handful of repeat viewers each day and write to them like a person.",
      "## Close the loop with a call to action",
      "End one update a day with a clear instruction: 'Reply YES for today's price' or 'DM me your size'. That gives silent viewers an easy first step and gives you a measurable result.",
      "Check your list once a day, note the repeat names, and follow up politely. Over a month this single habit builds a customer pipeline out of views you were already getting.",
    ],
  },
  {
    slug: "whatsapp-status-privacy-settings-explained",
    title: "WhatsApp Status Privacy Settings Explained: Who Sees What and How to Choose",
    description:
      "A plain-English guide to the three Status privacy options, how they affect your reach, and which setting is right for a business, a freelancer or a private user.",
    date: "2026-03-23",
    readMinutes: 5,
    tags: ["WhatsApp Status", "Privacy", "Settings"],
    body: [
      "WhatsApp gives you three ways to control who watches your Status. The right choice depends on whether you are trying to grow a business or protect your personal life, and many people use the wrong one by accident.",
      "## Where to find the setting",
      "Open WhatsApp, go to the Status tab, tap the three dots, and choose Status privacy. On iPhone it is in Settings, Privacy, Status. Changes apply to updates you post afterwards; they do not rewrite what you already shared.",
      "## Option 1: My contacts",
      "Everyone saved in your phone book can see your updates. This is the best choice for a business account because every new contact you add automatically becomes part of your audience.",
      "## Option 2: My contacts except",
      "You pick certain contacts to hide updates from. Use it when you run one number for both work and family and want to keep personal posts away from customers, or the other way round.",
      "## Option 3: Only share with",
      "You choose a specific list of people. This is useful for limited offers to loyal customers or for sharing private photos with close friends.",
      "## Why a business should rarely use the restricted options",
      "Every person you exclude is a missed sale. If you do need privacy, consider using two numbers: one for personal life, one for business. A dedicated business number keeps things clean and removes the temptation to hide updates.",
      "## Check the list regularly",
      "Exclusion lists are easy to forget. After a big contact import, open the privacy screen and confirm new contacts are not being filtered out by an old 'Only share with' list.",
      "## Pair it with read receipts",
      "Remember that turning off read receipts hides your viewer list as well. If you want to learn from your views, leave them on.",
      "Choose My contacts for growth, use exceptions sparingly, and review the setting any time you add a large group of new numbers.",
    ],
  },
  {
    slug: "best-time-to-post-whatsapp-status-nigeria",
    title: "Best Time to Post on WhatsApp Status in Nigeria: A Practical Schedule",
    description:
      "When Nigerians actually open WhatsApp Status, how to test your own best times, and a posting schedule you can follow whether you sell products or services.",
    date: "2026-03-30",
    readMinutes: 5,
    tags: ["WhatsApp Status", "Marketing", "Nigeria"],
    body: [
      "There is no single magic hour, but there are clear daily rhythms in how Nigerians use their phones. Posting into those windows gets more eyes on the same content at no extra cost.",
      "## The three natural windows",
      "Early morning, roughly 6:30 to 9:00am, when people check messages before leaving home. Midday, roughly 12:30 to 2:30pm, during lunch and work breaks. Evening, roughly 7:00 to 10:30pm, when most people are home and scrolling. These are starting points, not rules.",
      "## Match the time to your audience",
      "Students tend to be active late evening. Office workers peak at lunch and after work. Traders and market vendors are busy during the day and check in after closing. Think about when your customer is free, not when you are.",
      "## How to test your own best time",
      "For one week, post one similar update in each window and note the view count. The following week, repeat the best window and compare. After two weeks you will have real data from your own audience instead of guesses.",
      "## How many updates per day",
      "Three to five updates spread across the day works for most businesses. Posting everything at once pushes your earlier updates out of sight and increases the chance people mute you.",
      "## Weekends behave differently",
      "Sunday evening and Saturday morning often bring higher views for lifestyle, food and fashion content because people have more free time. Test heavier posting on those days.",
      "## Consider data and power cuts",
      "Many people browse on mobile data and skip videos when data is low. Short clips and clear photos perform better than long videos, especially outside the major cities.",
      "## Keep the rhythm consistent",
      "Consistency matters more than perfection. If people know you post a fresh offer every day at 1pm, they begin to look for it.",
      "Start with the three windows, track results for two weeks, and adjust. Your audience will tell you the best time if you measure it.",
    ],
  },
  {
    slug: "whatsapp-status-content-ideas-for-vendors",
    title: "25 WhatsApp Status Content Ideas for Nigerian Vendors (That Are Not Just Price Lists)",
    description:
      "Run out of things to post? Here are 25 proven Status ideas for product sellers and service providers, grouped by goal: trust, engagement and sales.",
    date: "2026-04-06",
    readMinutes: 6,
    tags: ["WhatsApp Status", "Content", "Marketing"],
    body: [
      "Most vendors post the same flyer every day and wonder why views fall. People watch Status for variety. Mix the ideas below and you will never stare at a blank screen again.",
      "## Trust-building ideas",
      "Show your workspace or shop in the morning. Film a short 'how it is made' clip. Post a customer's delivered order with their permission. Share a screenshot of a kind message from a customer, with the name hidden if they prefer. Introduce a member of your team. Explain your delivery process step by step.",
      "## Education ideas",
      "Give one quick tip related to your product, such as how to wash a fabric or how to store a gadget. Answer a question customers ask often. Compare two options and say which you recommend and why. Bust a common myth in your industry.",
      "## Engagement ideas",
      "Ask a one-tap question: 'Which colour do you prefer, A or B?' Run a simple quiz with the answer revealed in the next update. Ask people to reply with a word for a small giveaway. Share a poll-style question in the caption and invite replies.",
      "## Sales ideas",
      "Post a single product with one clear photo and one clear price. Announce a limited stock count. Share a bundle deal. Show a before and after. Post a countdown to the end of a promo. Remind people how to order in one line.",
      "## Personality ideas",
      "Share a short story about why you started. Post a lesson you learned from a mistake. Celebrate a small milestone like your hundredth order. Mark a public holiday or local event with a genuine message.",
      "## Seasonal and local ideas",
      "Tie posts to school resumption, festive seasons, rainy season, month-end salary periods and weekends. Local timing makes your content feel relevant instead of generic.",
      "## A simple weekly pattern",
      "Try this: Monday tip, Tuesday product, Wednesday customer story, Thursday behind the scenes, Friday offer, Saturday question, Sunday personal note. Repeat and adjust based on which days get replies.",
      "Aim for three value posts for every one direct sales post. People stay for the value and buy when they trust you.",
    ],
  },
  {
    slug: "whatsapp-status-captions-that-sell",
    title: "How to Write WhatsApp Status Captions That Get Replies and Orders",
    description:
      "Practical caption formulas for Nigerian small businesses, with examples of hooks, calls to action and common mistakes that make people scroll past.",
    date: "2026-04-13",
    readMinutes: 5,
    tags: ["WhatsApp Status", "Copywriting", "Sales"],
    body: [
      "A Status stays on screen for a few seconds. Your caption has to say what it is, why it matters and what to do next, in a handful of words.",
      "## Lead with the benefit, not the product",
      "Instead of 'New leather bags available', try 'Carry your laptop and lunch in one bag'. People respond to what the product does for them. Put the benefit first and the item second.",
      "## Use the one-idea rule",
      "One update, one message. If you try to sell three products in one caption, viewers remember none of them. Split it into separate updates.",
      "## Include the price when it is a selling point",
      "Hiding the price makes people send 'How much?' and then disappear. When your price is fair, show it. When it is premium, show the value first and the price second.",
      "## Add a clear call to action",
      "Tell people exactly how to respond: 'Reply 1 for the price list', 'Send your size to order', 'Tap my name to chat'. A small, specific step beats 'Contact me for more info'.",
      "## Create honest urgency",
      "Real limits work: 'Only 6 left', 'Delivery slots for Saturday are almost full'. Fake countdowns that restart every day damage trust quickly, so only use urgency you can back up.",
      "## Write the way you speak",
      "Short sentences, familiar words, a bit of local flavour where it suits your brand. Avoid long paragraphs and heavy punctuation.",
      "## Keep the text readable on a photo",
      "If you place text on the image, use high contrast, large font and never cover the product. Test it by viewing the update on a small phone before posting.",
      "## Mistakes to avoid",
      "Posting only screenshots of other people's flyers, writing in all capitals, using too many emojis, and forgetting to say how to order. Each one lowers your reply rate.",
      "Test two caption styles over a week, keep the one that earns more replies, and refine it. Small wording changes add up to noticeably more orders.",
    ],
  },
  {
    slug: "product-photos-with-your-phone-for-whatsapp-status",
    title: "How to Take Professional Product Photos With Just Your Phone",
    description:
      "Lighting, background, angles and editing tips that make your phone photos look professional on WhatsApp Status, without buying any expensive equipment.",
    date: "2026-04-20",
    readMinutes: 6,
    tags: ["Photography", "WhatsApp Status", "Small Business"],
    body: [
      "Good photos are the cheapest upgrade a small business can make. You do not need a studio or a new phone, only light, a clean background and a few minutes of care.",
      "## Use natural light",
      "Shoot near a window in the morning or late afternoon. Soft daylight flatters products and avoids the harsh shadows of a ceiling bulb. Do not use direct midday sun on shiny items, because it creates glare.",
      "## Avoid the flash",
      "The built-in flash flattens colours and creates hot spots on glossy surfaces. If the room is dark, move closer to a window or use a desk lamp with a white bulb.",
      "## Choose a simple background",
      "A plain white sheet, a clean table or a neutral wall keeps attention on the product. Remove clutter, cables and personal items from the frame.",
      "## Clean the lens",
      "A smudged lens is the most common reason photos look hazy. Wipe it with a soft clean cloth before every session.",
      "## Shoot from a few angles",
      "Take a front view, a close detail shot and one photo that shows the product in use or next to something for scale. Customers like seeing size and texture.",
      "## Hold the phone steady",
      "Rest your elbows on a table or lean the phone against something. Tap the product on screen to focus and slide the brightness slightly down if highlights look washed out.",
      "## Edit lightly",
      "Crop to a vertical frame, raise brightness a little and reduce clutter. Heavy filters change product colour, which leads to complaints when the real item arrives.",
      "## Keep colours honest",
      "Customers buy what they see. If a dress looks deep blue in the photo and navy in person, say so. Honest photos reduce returns and build repeat business.",
      "## Batch your shoots",
      "Spend one hour each week photographing a full week of products. It is faster than shooting daily and gives your Status a consistent look.",
    ],
  },
  {
    slug: "short-videos-for-whatsapp-status-that-people-watch",
    title: "How to Make Short Videos for WhatsApp Status That People Watch to the End",
    description:
      "A beginner-friendly guide to filming, editing and posting short vertical videos for WhatsApp Status, including hooks, pacing, file size and data-friendly tips.",
    date: "2026-04-27",
    readMinutes: 5,
    tags: ["Video", "WhatsApp Status", "Marketing"],
    body: [
      "Video earns more attention than still images, but only when it is quick and clear. Aim for videos that make a single point in the first few seconds.",
      "## Film vertically",
      "Hold your phone upright. Status is a full-screen vertical format, and horizontal clips show with black bars that make the product look small.",
      "## Open with a hook",
      "The first two seconds decide whether people keep watching. Start with the result, a surprising detail or a direct question, not a logo or a long greeting.",
      "## Keep it short",
      "Short clips finish more often. WhatsApp also trims longer videos into separate segments, which breaks the flow of your message. Plan for a single clip with one clear idea.",
      "## Show, do not just tell",
      "Demonstrate the product being used: pouring, unboxing, fitting, measuring, cooking. Movement keeps people watching longer than a static shot.",
      "## Make sure the audio works",
      "Many people watch with the sound off, so add captions or on-screen text for the key message. If you speak, record somewhere quiet and hold the phone close.",
      "## Light and steady",
      "Film near a window and keep the camera steady. A shaky, dark video looks careless even when the product is excellent.",
      "## Keep file sizes friendly",
      "Large uploads fail on weak networks and cost viewers data. Record in standard HD rather than the highest setting, and trim dead time at the start and end.",
      "## End with a clear next step",
      "Finish with a line like 'Reply to order' or 'Message me for the price'. Without it, viewers enjoy the clip and move on.",
      "Post one video a day for two weeks, compare the replies with your photo posts, and keep whichever format works for your audience.",
    ],
  },
  {
    slug: "whatsapp-business-app-setup-nigeria",
    title: "WhatsApp Business App Setup in Nigeria: A Complete Step-by-Step Guide",
    description:
      "How to install the WhatsApp Business app, verify your number, build a trustworthy business profile and set up greeting and away messages the right way.",
    date: "2026-05-04",
    readMinutes: 7,
    tags: ["WhatsApp Business", "Setup", "Tutorial"],
    body: [
      "The free WhatsApp Business app is built for small companies. It lets you show a proper business profile, organise customers and automate a few repetitive messages, while still using your normal phone number.",
      "## Before you start",
      "Choose the number you want customers to use. Ideally it should be a dedicated business line, not your personal number, so work and private life stay separate. Back up your chats if you plan to move an existing number.",
      "## Install and verify",
      "Download WhatsApp Business from the Play Store or App Store and open it. Accept the terms, enter your number and confirm the verification code sent by SMS or call. If you migrate a number from the regular app, follow the prompts so your chats transfer.",
      "## Build your business profile",
      "Add your business name, a clear logo or product photo, a short description, your category, address if you have a shop, opening hours, email and website or social link. Complete profiles look more trustworthy and answer common questions before customers ask.",
      "## Set a greeting message",
      "A greeting replies automatically to new customers. Keep it short and useful: say hello, state your hours and tell them how to order. Avoid long paragraphs that nobody reads.",
      "## Set an away message",
      "Use this outside working hours so customers know when to expect a reply. It prevents frustration and shows you are organised.",
      "## Add quick replies and labels",
      "Save answers to your top questions, such as price, delivery and payment details, and use labels to mark new customers, pending payment and completed orders. These two features save hours every week.",
      "## Add a catalog",
      "Upload your best products with clear photos, prices and short descriptions. Customers can browse without asking for a flyer every time.",
      "## Protect the account",
      "Turn on two-step verification and keep your phone number active. Do not link the account to unofficial apps or mods, which can lead to restrictions.",
      "Take twenty minutes to complete each of these steps and your number will look like a real business from the first message.",
    ],
  },
  {
    slug: "whatsapp-business-catalog-guide",
    title: "WhatsApp Business Catalog: How to Showcase Products So Customers Stop Asking 'Price?'",
    description:
      "Learn how to build a clear WhatsApp Business catalog with great photos, honest descriptions and organised collections that turn browsers into buyers.",
    date: "2026-05-11",
    readMinutes: 5,
    tags: ["WhatsApp Business", "Catalog", "Sales"],
    body: [
      "A catalog is a mini shop inside your WhatsApp profile. Customers can browse items, see prices and message you about a specific product with one tap, which saves both sides a lot of back and forth.",
      "## How to open the catalog",
      "In the WhatsApp Business app, open Settings, tap your business name, then choose Catalog. Add a new item, upload up to several photos, and fill in the details.",
      "## What each item needs",
      "A clear name, a price, a short description and at least one sharp photo. Add a product code or size information if it helps customers pick correctly. If an item is custom, say how long it takes to make.",
      "## Write descriptions that answer questions",
      "Mention material, size, colour, what is included and delivery notes. If you answer the questions people ask most, you reduce messages that go nowhere.",
      "## Use collections",
      "Group products into categories such as Men, Women, Kitchen or Services. Customers find what they want faster when the catalog is organised instead of one long list.",
      "## Keep photos consistent",
      "Use the same background and lighting across the catalog so it looks like one brand. Update photos when your stock changes.",
      "## Share your catalog link",
      "Every catalog can be shared as a link. Add it to your Status, your Instagram bio and your email signature so people can browse without having to ask.",
      "## Keep it current",
      "Remove sold-out items or mark them unavailable. Nothing damages trust like asking for a product that is no longer in stock.",
      "## Pair it with your Status",
      "Use Status to show new arrivals and the catalog to hold the full range. Status creates attention, the catalog makes buying easy.",
      "A tidy, accurate catalog works for you around the clock and gives serious buyers a reason to message you with their order instead of a question.",
    ],
  },
  {
    slug: "quick-replies-and-labels-whatsapp-business",
    title: "WhatsApp Business Quick Replies and Labels: Save Hours Every Week",
    description:
      "How to set up quick replies, labels and automated messages in WhatsApp Business so you can respond faster and keep every order organised.",
    date: "2026-05-18",
    readMinutes: 5,
    tags: ["WhatsApp Business", "Productivity", "Customer Service"],
    body: [
      "If you type the same answers fifty times a day, you are doing work your phone can do for you. Quick replies and labels turn a messy inbox into a simple system.",
      "## What quick replies do",
      "A quick reply is a saved message you can insert by typing a forward slash and its shortcut. For example, typing /price could insert your full price list, and /bank could insert your payment details.",
      "## How to create one",
      "In WhatsApp Business open Settings, then Business tools, then Quick replies. Tap add, write the message, and choose a shortcut. Keep the shortcut short and easy to remember.",
      "## Useful quick replies to start with",
      "A friendly welcome, your price list, delivery areas and fees, payment details, opening hours, a thank-you after purchase, and a polite request for a review. These cover most daily conversations.",
      "## Edit before you send",
      "Quick replies appear in the message box, so you can personalise the first line with the customer's name. A message that sounds copied is less persuasive than one that sounds personal.",
      "## What labels do",
      "Labels are colour tags you attach to chats. They let you filter your inbox by status, so nothing falls through the cracks.",
      "## A simple label system",
      "New customer, interested, awaiting payment, paid, delivered, and follow up later. Move each chat through the labels as the order progresses and check the awaiting payment label every evening.",
      "## Combine labels with reminders",
      "Review the follow up label at a fixed time each day. A friendly nudge after a day or two recovers many sales that would otherwise be forgotten.",
      "## Do not over-automate",
      "Automated greetings and replies should help, not replace real conversation. Use them to handle the routine, then step in personally when a customer is ready to buy.",
      "Spend half an hour setting these up once and you will gain that time back every single day.",
    ],
  },
  {
    slug: "whatsapp-broadcast-list-vs-status-vs-groups",
    title: "WhatsApp Broadcast Lists vs Status vs Groups: Which Should Your Business Use?",
    description:
      "A clear comparison of the three main WhatsApp promotion channels, how each one works, their limits, and the best way to combine them without annoying customers.",
    date: "2026-05-25",
    readMinutes: 6,
    tags: ["WhatsApp", "Marketing", "Strategy"],
    body: [
      "WhatsApp offers several ways to reach people at once, and each behaves differently. Choosing the wrong one wastes effort and can irritate the very people you want to win.",
      "## WhatsApp Status",
      "Status is a 24-hour update that appears in a separate tab. It reaches people who have saved your number and chosen to watch. It is passive, low pressure and ideal for awareness, trust and new product reveals.",
      "## Broadcast lists",
      "A broadcast list sends one message to many people individually, and replies come back as private chats. Recipients must have your number saved to receive it, and each list has a limit on how many people it can hold, commonly 256. It works well for order updates and special offers to existing customers.",
      "## Groups",
      "Groups let everyone talk to each other. They suit communities, clubs or customers who benefit from conversation, but they can get noisy and members often mute them. Rules and moderation are essential.",
      "## Which one for which goal",
      "Use Status to attract and warm up people. Use broadcast lists for permission-based updates to buyers. Use groups for communities with shared interest, like a training class or an alumni circle.",
      "## Respect consent",
      "Only add people to a list or group who agree to it. Adding strangers without asking leads to blocks and reports, which can harm your account.",
      "## Do not blast",
      "Even with consent, sending too many messages makes people leave. One or two useful messages a week is a healthy limit for a broadcast list.",
      "## A combined approach",
      "Post daily on Status, send a weekly offer through a broadcast list to customers who asked for updates, and keep one active group for your most loyal buyers. Each channel supports the others.",
      "Choose the channel that matches your goal, stay within the rules and always give people an easy way to opt out.",
    ],
  },
  {
    slug: "fix-vcf-import-not-working-android",
    title: "VCF Import Not Working on Android? Common Errors and How to Fix Them",
    description:
      "Troubleshoot VCF import problems on Android, from 'cannot open file' errors to missing contacts, with simple fixes including the Google Contacts web method.",
    date: "2026-06-01",
    readMinutes: 6,
    tags: ["VCF", "Android", "Troubleshooting"],
    body: [
      "Most VCF import problems come down to a handful of causes. Work through the list below from top to bottom and you will almost always find the answer.",
      "## Error: 'Cannot open file' or 'No vCard found'",
      "The file may not have finished downloading, or it was opened from a messaging app preview. Move to your Downloads folder, confirm the file name ends in .vcf, and import it again from within the Contacts app rather than tapping it in a chat.",
      "## Nothing happens when you tap the file",
      "Some phones do not know which app should handle VCF files. Open the Contacts app, go to the menu, Settings, Import, and select the file manually.",
      "## Import completes but contacts are missing",
      "Check which account the contacts were saved to. In Contacts settings, make sure All contacts or the right Google account is displayed. Contacts saved to an inactive SIM or hidden account will appear to be missing.",
      "## The file is very large",
      "Importing several thousand contacts at once can freeze weaker phones. Wait a few minutes before assuming it failed. If it still stalls, use the browser method below.",
      "## The Google Contacts browser method",
      "On a computer or in a mobile browser set to desktop view, open contacts.google.com, choose Import from the left menu, upload the .vcf file and confirm. The contacts then sync to your phone automatically. This is the most reliable way to handle large files.",
      "## Storage and permission problems",
      "If your phone is almost full, imports can fail silently. Free up space and make sure the Contacts app has permission to read files.",
      "## File got corrupted",
      "Interrupted downloads create broken files. Delete the file and download it again over a stable connection. Avoid opening the file in a text editor and saving it, which can change the encoding.",
      "## Restart and retry",
      "Restart the phone, clear the Contacts app cache in App settings, and try again. If one method fails, another will usually work.",
      "Once the import succeeds, wait for sync to finish and refresh your WhatsApp contact list so the new numbers appear.",
    ],
  },
  {
    slug: "remove-duplicate-contacts-android-iphone",
    title: "How to Remove Duplicate Contacts on Android and iPhone in Minutes",
    description:
      "Clean up duplicate contacts after a bulk import using built-in tools on Google Contacts and iPhone, with tips to prevent duplicates in future.",
    date: "2026-06-08",
    readMinutes: 5,
    tags: ["Contacts", "Tutorial", "Phone Tips"],
    body: [
      "Duplicates build up after repeated imports, old backups and syncing across several accounts. They make your phone book messy and waste storage, but cleaning them takes only a few minutes.",
      "## On Android with Google Contacts",
      "Open the Google Contacts app, tap Fix & manage, then Merge & fix. If duplicates are found, you will see a Merge duplicates suggestion. Review it and tap Merge all, or merge selected groups one by one.",
      "## Using Google Contacts on a computer",
      "Go to contacts.google.com and choose Merge & fix from the left menu. The larger screen makes it easier to review bigger lists. Always check a few sample merges before accepting them all.",
      "## On iPhone",
      "Open the Contacts app. Newer versions of iOS offer a Duplicates Found notice at the top of the list when matching entries exist. Tap it and choose Merge All Duplicates or review them individually. If you do not see it, there may be nothing to merge.",
      "## Using iCloud on a computer",
      "Sign in to icloud.com, open Contacts, select the contacts you want to clean, and merge or delete them from the settings menu. This is useful for very large lists.",
      "## Back up first",
      "Before you merge or delete anything, export your contacts as a VCF file. That way you can restore the list if something is merged incorrectly.",
      "## Why duplicates happen",
      "Importing the same file twice, saving the same number under different names, and keeping contacts in both the phone storage and Google account. Choose one main account and save everything there.",
      "## Prevent future duplicates",
      "Use a consistent naming pattern, import each file only once and avoid re-importing old backups. Good platforms send you only numbers you have not received before, which prevents most duplicates at the source.",
      "A clean contact list also helps WhatsApp sync faster and makes it easier to find the people who matter.",
    ],
  },
  {
    slug: "delete-imported-contacts-after-vcf-import",
    title: "How to Delete Imported Contacts After a VCF Import (Without Losing Your Own)",
    description:
      "Imported too many contacts or want a fresh start? Learn how to remove a VCF batch safely on Google Contacts, Android and iPhone while keeping your personal contacts.",
    date: "2026-06-15",
    readMinutes: 5,
    tags: ["VCF", "Contacts", "Tutorial"],
    body: [
      "Sometimes you want to clear out a batch of imported numbers, perhaps because you hit a storage limit or you simply want a clean slate. The key is to remove only the imported group and leave your real contacts alone.",
      "## Start with a backup",
      "Export your full contact list as a VCF file first. If you delete the wrong entries, you can import the backup and recover them.",
      "## Method 1: Undo changes in Google Contacts",
      "If you imported recently, open Google Contacts, go to Fix & manage, and choose Undo changes. You can roll back to a point in time within the last 30 days. Be careful, because this undoes every change made after that time, not only the import.",
      "## Method 2: Use the import label",
      "Google Contacts usually creates a label for each import, named with the import date. Open that label, select all contacts inside it, and delete them. Your other contacts remain untouched because they are not in that label.",
      "## Method 3: Search by naming pattern",
      "If the imported contacts share a naming pattern, such as 'Status Connect 000142', search for the common words in Google Contacts, select all search results, and delete them. A consistent name is the easiest way to find and remove a whole batch.",
      "## On iPhone",
      "Go to Contacts, open Lists, and look for the group the import created. You can also search by the shared name and delete in groups. For very large deletions, use icloud.com on a computer, select the contacts and delete them there.",
      "## On Android without Google sync",
      "Open the Contacts app, search the shared name, long-press one entry, select all and delete. Make sure you are not selecting contacts from another source.",
      "## Check WhatsApp afterwards",
      "Refresh your WhatsApp contact list so removed numbers no longer appear. Remember that deleting a contact also removes their ability to see your Status through that saved link.",
      "## Think before you delete",
      "Every number you remove is a person who could have seen your updates. If storage is the problem, consider cleaning duplicates first rather than deleting active contacts.",
    ],
  },
  {
    slug: "back-up-contacts-android-iphone-google",
    title: "How to Back Up Your Phone Contacts So You Never Lose Customers",
    description:
      "A simple guide to backing up contacts on Android and iPhone using Google, iCloud and a VCF export, with a schedule so your customer list is always safe.",
    date: "2026-06-22",
    readMinutes: 5,
    tags: ["Contacts", "Backup", "Phone Tips"],
    body: [
      "For a vendor, the contact list is the business. A lost, stolen or broken phone can wipe out years of customer relationships in a minute, yet most people never back up their contacts.",
      "## Back up on Android with Google",
      "Open Settings, then Google, then Backup, and make sure contacts are syncing to your Google account. You can also check in Settings, Accounts, Google, Account sync, and confirm Contacts is on. Open contacts.google.com on any browser to verify your list is there.",
      "## Back up on iPhone with iCloud",
      "Go to Settings, tap your name, open iCloud, and switch Contacts on. Your list is then stored online and restored when you sign in on a new device.",
      "## Export a VCF file as a second copy",
      "In Google Contacts choose Export, select all contacts and the vCard format, and download the file. On iPhone, use icloud.com, select all contacts and choose Export vCard. Save the file somewhere safe.",
      "## Keep the file in more than one place",
      "Store a copy on your computer, in cloud storage and perhaps on a USB drive. A single backup in one location is not much better than no backup.",
      "## Back up on a schedule",
      "Put a monthly reminder in your calendar to export a fresh file. If you add a lot of contacts, do it more often, for example after each large import.",
      "## Secure your backups",
      "A contact file contains private information. Do not share it publicly, and protect cloud accounts with a strong password and two-step verification.",
      "## Test the restore",
      "Once a year, import your backup into a new Google account or spare phone to confirm it works. A backup that cannot be restored is not a backup.",
      "## Before you change phones",
      "Confirm sync is complete, export a VCF, then sign in on the new device and check that the number of contacts matches before wiping the old one.",
    ],
  },
  {
    slug: "how-many-contacts-can-you-save-on-your-phone",
    title: "How Many Contacts Can You Save on Android and iPhone? Limits and Smart Workarounds",
    description:
      "Understand storage and account limits for saving contacts on Android, iPhone and Google, plus practical ways to manage a very large contact list.",
    date: "2026-06-29",
    readMinutes: 5,
    tags: ["Contacts", "Phone Tips", "VCF"],
    body: [
      "People who exchange contacts regularly eventually ask the same question: is there a limit? The honest answer is that it depends on where you save the contacts and how much space your phone has.",
      "## Google account limit",
      "Google Contacts allows a very large list, with a published limit of 25,000 contacts per account. For most people that is more than enough, but heavy networkers can approach it, so it is worth checking how many you have.",
      "## Phone storage",
      "Contacts take very little space individually, since each one is just text. A list of thousands usually uses a few megabytes. The phone slowing down is more often caused by duplicates and syncing than by raw size.",
      "## SIM card",
      "SIM cards hold only a small number of contacts, often a few hundred, and they store limited details. Save contacts to your Google or iCloud account instead.",
      "## iPhone and iCloud",
      "iCloud stores contacts alongside your other data and counts toward your overall storage plan, though contacts use very little. Large lists mostly cause trouble when syncing across devices.",
      "## WhatsApp itself",
      "WhatsApp reads whatever is in your address book. The practical limit is how fast your phone can sync, so extremely large imports may take a while to appear.",
      "## Managing a big list",
      "Use labels or groups to organise contacts, for example customers, suppliers and community. Use a consistent naming pattern so search is quick.",
      "## Keep it healthy",
      "Merge duplicates, remove numbers that are clearly invalid, and back up regularly. A smaller clean list works better than a huge messy one.",
      "## Split large imports",
      "If a very large file stalls your phone, import it in parts or use Google Contacts in a browser. Splitting gives your phone time to sync without freezing.",
      "Know your account limit, back up often and keep things tidy, and a large network will stay easy to manage.",
    ],
  },
  {
    slug: "two-step-verification-whatsapp-business-number",
    title: "How to Protect Your WhatsApp Business Number With Two-Step Verification",
    description:
      "Learn how to switch on two-step verification, add a recovery email, and stop hijackers from stealing your WhatsApp number and customers.",
    date: "2026-07-06",
    readMinutes: 5,
    tags: ["Security", "WhatsApp Business", "Safety"],
    body: [
      "Account takeover is one of the most painful things that can happen to a small business. A stolen WhatsApp number means lost customers, fake messages sent in your name and weeks of recovery. Two-step verification is the strongest simple defence.",
      "## How the common attack works",
      "A scammer registers your number on their phone, which triggers a six-digit code sent by SMS to you. Then they message you, pretending to be a friend or WhatsApp support, and ask you to share the code. If you do, they take over the account.",
      "## Never share your verification code",
      "No genuine friend, customer or WhatsApp staff member will ask for your six-digit code. If someone does, it is an attempt to steal your account. Stop the conversation and warn others.",
      "## Switch on two-step verification",
      "Open WhatsApp, go to Settings, Account, Two-step verification, and enable it. Create a six-digit PIN that is not your birthday or phone number.",
      "## Add a recovery email",
      "WhatsApp will ask for an email address. Use one you can access, because it is how you reset the PIN if you forget it. Confirm the email so it is active.",
      "## Remember the PIN",
      "WhatsApp occasionally asks for the PIN to confirm it is really you. Store it in a trusted password manager or somewhere private, not in a note named PIN on your phone.",
      "## Check linked devices",
      "Go to Settings, Linked devices and review the list. Log out of any device you do not recognise or no longer use.",
      "## Secure your SIM",
      "Register your SIM with your network provider using your own details and report a lost phone quickly to have the line blocked. A stolen SIM can lead to a stolen WhatsApp.",
      "## If you are locked out",
      "Reinstall WhatsApp, enter your number and use the recovery email option. If a thief took over, use the in-app option to contact support and tell your contacts through another channel.",
    ],
  },
  {
    slug: "whatsapp-account-restricted-or-banned-what-to-do",
    title: "WhatsApp Account Banned or Restricted? What to Do and How to Avoid It Next Time",
    description:
      "Why WhatsApp accounts get banned or restricted, how to request a review through the official in-app process, and habits that keep your business number safe.",
    date: "2026-07-13",
    readMinutes: 6,
    tags: ["Compliance", "WhatsApp", "Safety"],
    body: [
      "Seeing a message that your account is banned or restricted is stressful, especially when your business depends on it. The good news is that you can often take steps to get help, and prevention is simpler than most people think.",
      "## Common reasons accounts are limited",
      "Using modified apps such as GB versions, sending large numbers of messages to people who did not ask for them, being reported or blocked by many users, using automation tools, and adding people to groups without consent. WhatsApp looks at behaviour patterns, not just intentions.",
      "## Restricted versus banned",
      "A restriction is usually temporary and limits some features, such as sending to new contacts. A ban is more serious. The message on screen tells you which one you have and what you can do next.",
      "## Request a review in the app",
      "If WhatsApp shows a banned message, tap the option to request a review. Add a short, honest explanation that you use the account for legitimate business and have not broken the rules. Avoid long angry messages.",
      "## Contact support",
      "You can also reach support from the app's Help section or through the official WhatsApp contact page. Use only official channels. Beware of people online who promise to unban any number for a fee, because many of them are scammers.",
      "## Stop using unofficial apps immediately",
      "If you used a modified app, uninstall it and move to the official WhatsApp or WhatsApp Business app before applying for review. Continuing to use it risks repeat bans.",
      "## Wait and be patient",
      "Reviews can take time. Repeated requests do not speed things up and may slow the process.",
      "## Prevent the next ban",
      "Only message people who expect to hear from you. Slow down when messaging new contacts. Do not use bulk tools. Encourage customers to save your number first so they see your Status instead of receiving unsolicited messages.",
      "## Keep a backup plan",
      "Back up your contacts, keep key customer details outside WhatsApp, and consider a second channel such as Instagram or a Telegram page. A single point of failure is risky for any business.",
    ],
  },
  {
    slug: "spot-whatsapp-scams-nigeria",
    title: "10 Common WhatsApp Scams in Nigeria and How to Spot Them Before You Lose Money",
    description:
      "Learn the warning signs of fake alerts, cloned accounts, code theft and fake job offers on WhatsApp, with clear steps to protect yourself and your customers.",
    date: "2026-07-20",
    readMinutes: 6,
    tags: ["Safety", "Scams", "Nigeria"],
    body: [
      "Scammers go where people are, and millions of Nigerians use WhatsApp every day. Knowing the common tricks makes you a much harder target.",
      "## 1. Verification code theft",
      "Someone asks you to send a six-digit code 'sent to you by mistake'. That code lets them take over your account. Never share it.",
      "## 2. Cloned accounts",
      "A scammer copies a friend's photo and name on a new number and asks for urgent money. Always call the person on their known number before sending anything.",
      "## 3. Fake payment alerts",
      "A buyer shows a screenshot of a transfer or sends a fake SMS alert. Confirm payments only inside your bank app or official alert, never from a picture.",
      "## 4. Overpayment tricks",
      "A buyer 'accidentally' pays too much and asks you to refund the difference. Check that the original money is really in your account before you return anything.",
      "## 5. Fake job offers",
      "Offers that ask you to pay for registration, training or equipment before you start are almost always scams. Real employers do not charge applicants.",
      "## 6. Investment and doubling schemes",
      "Promises of guaranteed returns or doubled money in days are red flags. If it sounds too good to be true, it is.",
      "## 7. Fake giveaways and links",
      "Messages claiming you won a prize or data offer ask you to click a link and enter details. Do not click unknown links, and never type your bank or login details into a page that came from a stranger.",
      "## 8. Impersonating customer care",
      "Scammers pose as bank or network staff. Real institutions do not ask for your PIN, password or full card details over WhatsApp.",
      "## 9. Fake delivery and logistics demands",
      "Someone claims your parcel is held and asks for a clearance fee. Confirm with the actual courier using details you found yourself.",
      "## 10. Romance and friendship traps",
      "A new contact builds trust over weeks and then asks for help. Be careful with anyone who will not video call and always has an emergency.",
      "Slow down, verify through a second channel and report suspicious accounts using the in-app report option. A short pause protects your money and your reputation.",
    ],
  },
  {
    slug: "accept-payments-safely-whatsapp-sales-nigeria",
    title: "How to Accept Payments Safely When Selling on WhatsApp in Nigeria",
    description:
      "A practical checklist for confirming transfers, avoiding fake alerts and building a payment process that protects both you and your customers.",
    date: "2026-07-27",
    readMinutes: 5,
    tags: ["Payments", "Safety", "Small Business"],
    body: [
      "Selling is only complete when real money reaches your account. A safe, repeatable payment process protects you from fraud and gives customers confidence to pay.",
      "## Use one clear payment method",
      "Give customers a single account name and number that matches your business or your registered name. Save it as a quick reply so you never mistype it.",
      "## Confirm payments in your bank app",
      "Never release goods based on a screenshot, a forwarded alert or someone saying they have paid. Open your bank app or official statement and check that the credit is real and complete.",
      "## Watch for pending or reversed transfers",
      "Some fake payments show as pending and later fail. Wait until the credit is fully posted before shipping, especially for expensive items.",
      "## Ask for proof of payment, then verify",
      "Receipts are useful for your records, but treat them as a courtesy, not as proof. Verification always happens on your side.",
      "## Be careful with refunds",
      "If a customer pays too much and wants a refund, refund only after the original money is confirmed and settled. Many scams depend on you acting quickly.",
      "## Use a payment link or business account",
      "Consider a payment gateway or business account that generates payment links and receipts. It reduces the risk of manual errors and looks more professional.",
      "## Deposit for custom orders",
      "For made-to-order items, take a deposit before you start and the balance before delivery. Put the terms in writing in the chat.",
      "## Keep records",
      "Save invoices, receipts and chats in a folder or spreadsheet. Good records help with tax, disputes and understanding your real profit.",
      "## Pay on delivery with care",
      "If you offer it, use a trusted dispatch rider and confirm the order is genuine first. Many fake orders are placed just to waste a vendor's time.",
      "A clear process, verified payments and good records make your business safer and make customers trust you more.",
    ],
  },
  {
    slug: "how-to-price-products-on-whatsapp-nigeria",
    title: "How to Price Your Products on WhatsApp in Nigeria and Still Make a Profit",
    description:
      "A simple pricing method for small sellers: calculate real costs, set a healthy margin, handle negotiation and avoid the mistakes that quietly kill profit.",
    date: "2026-08-03",
    readMinutes: 6,
    tags: ["Pricing", "Small Business", "Sales"],
    body: [
      "Many small sellers price by copying a competitor and guessing a margin. That works until costs rise and profit disappears. A little arithmetic gives you prices you can defend.",
      "## Start with your true cost",
      "Add the purchase or production cost, packaging, transport, data and phone use, platform or payment fees, and a share of your own time. If you ignore any of these, your real profit is smaller than you think.",
      "## Decide your margin",
      "Choose a profit percentage that covers growth and emergencies, not only survival. Different products can carry different margins; fast sellers can accept lower ones, while rare or custom items should earn more.",
      "## Check the market",
      "Look at what similar sellers charge, but do not simply copy them. They may have different costs, different quality or be selling at a loss. Use the market as a range, not a rule.",
      "## Price by value, not only cost",
      "If your product saves time, looks better or comes with better service, you can charge more. Show that value in your photos, descriptions and reviews.",
      "## Plan for negotiation",
      "Nigerian buyers often negotiate. Build a small buffer into your first price so you can offer a discount and still keep your margin. Decide your lowest acceptable price before the conversation starts.",
      "## Offer bundles instead of cuts",
      "Instead of lowering the price, add a small free item or offer a better price for two items. You protect your margin and increase the order size.",
      "## Review prices regularly",
      "Costs change with fuel, exchange rates and supplier prices. Review your prices every month and update your catalog when needed.",
      "## Be transparent",
      "Tell customers when prices change and why. Honest communication keeps regular buyers loyal.",
      "Know your costs, protect your margin and communicate value, and your pricing will support the business instead of draining it.",
    ],
  },
  {
    slug: "handle-customer-complaints-on-whatsapp",
    title: "How to Handle Customer Complaints on WhatsApp Without Losing the Customer",
    description:
      "A calm, step-by-step approach to complaints, delays and refund requests that protects your reputation and often turns upset buyers into loyal ones.",
    date: "2026-08-10",
    readMinutes: 5,
    tags: ["Customer Service", "Small Business", "Reputation"],
    body: [
      "A complaint feels personal, but it is also an opportunity. Customers who are treated well after a problem often become your most loyal buyers.",
      "## Respond quickly",
      "Reply as soon as you can, even if you do not have the answer yet. A short message saying you are checking and will update them within the hour calms most situations.",
      "## Listen before defending",
      "Let the customer explain everything first. Avoid interrupting with excuses. Repeat the problem back to them so they know you understood.",
      "## Apologise sincerely",
      "A simple, honest apology costs nothing: 'I am sorry this happened, and I want to fix it.' Do not blame the customer or the rider in your first reply.",
      "## Gather facts calmly",
      "Ask for photos, order details or the date and time of delivery. Check your own records. Stay polite even if the tone gets sharp.",
      "## Offer a clear solution",
      "Depending on the issue, offer a replacement, a repair, a partial refund or a discount on the next order. Give a specific timeline so they know what to expect.",
      "## Follow through",
      "Do exactly what you promised, when you promised. Missing a second deadline does more damage than the original problem.",
      "## Move heated chats to a calmer tone",
      "If the customer is angry, keep your messages short and respectful. Avoid arguing in front of others, and never post private chats to shame a customer.",
      "## Learn from patterns",
      "Keep a list of recurring complaints, such as late delivery or wrong sizes. Fix the root cause, update your descriptions or change your process.",
      "## Ask for feedback after fixing it",
      "Once the problem is resolved, thank the customer and ask if they are satisfied. Many will happily share a positive review or order again.",
    ],
  },
  {
    slug: "freelancers-find-clients-on-whatsapp-nigeria",
    title: "How Nigerian Freelancers Can Find Clients on WhatsApp Without Spamming",
    description:
      "A realistic client-finding system for designers, writers, developers, tutors and other freelancers, using Status, contact exchange and professional follow-up.",
    date: "2026-08-17",
    readMinutes: 6,
    tags: ["Freelancing", "Networking", "Nigeria"],
    body: [
      "Freelancers often hear that they should message hundreds of strangers. That approach gets numbers blocked and reputations damaged. A better way is to let the right people see your work repeatedly and reach out when they need you.",
      "## Define who you help",
      "Be specific: 'I design logos for small food businesses' is easier to remember than 'I do graphics'. A clear niche makes it easy for people to refer you.",
      "## Build a proper profile",
      "Use a clear photo, a short line about what you do and a link to your portfolio. If you use WhatsApp Business, fill in the description and catalog with your services and starting prices.",
      "## Grow your network of relevant contacts",
      "Join communities where business owners are active and exchange contacts with them. Business owners need designers, writers, accountants, developers and tutors, so they are your future clients.",
      "## Use Status as your portfolio",
      "Post one finished project or result each day with a short story behind it: the problem, what you did, the outcome. Case studies convince more than lists of skills.",
      "## Share useful tips",
      "Teach something small related to your service. It proves your skill and reminds people you exist when they need help.",
      "## Respond fast and professionally",
      "When someone asks about your service, reply with a clear scope, timeline and price range. Quick, clear answers win more jobs than low prices.",
      "## Use deposits and written scope",
      "Agree on deliverables, revisions and payment terms in writing, and collect a deposit before starting. This protects you from unpaid work and scope creep.",
      "## Ask for testimonials and referrals",
      "After a successful project, ask for a short review you can share and ask if they know anyone else who needs the service. Referrals are the cheapest source of clients.",
      "## Follow up politely",
      "If a prospect goes quiet, send one friendly follow-up after a few days. Then let it go. Persistence is good, pressure is not.",
      "Show your work daily, build your network with real business people and treat each client well, and the messages will start coming to you.",
    ],
  },
];
